### ISSUE TITLE
Add command: Go to start of line

### ISSUE THREAD

**Issue by matthewrsj** [matthewrsj/kilo#10]

**Comment by milto-github** [comment]
Hey, I submitted a pull request implementing going to the start/end of line. Are you the one that got the request or the other guy?

**Comment by matthewrsj** [comment]
Hey @mndrenika I would love to see your PR. I'm the guy you forked from, but not the guy that got the request.

**Comment by milto-github** [comment]
@matthewrsj I'm having trouble with my VM at the moment, but I submitted a file change request. Did you get it?

**Comment by matthewrsj** [comment]
Nope, not yet. This is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/12090084/20200869/b1f08c6a-a768-11e6-81dc-aaa2e8b71767.png)

No pull requests. 

This document might help you if you are having issues: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by matthewrsj** [comment]
@mndrenika thanks for you contribution! Fixed by #12
